server:
  port: 111

system:
  conf:
    active: prod
    listener: com.sunny.sample.SampleConfProcessListener
  dynamic:
    interval: 5
    unit: s

test:
  a: 1
  b: 2
  c: 3
  d: 5

dynamic:
  test: 123